name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Use Firebase config
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          echo "$FIREBASE_CONFIG" > firebase-config.json

      - name: Deploy to server
        run: |
          
          # Utilize o arquivo firebase-config.json conforme necessário
          # por exemplo, para configurar um serviço ou fazer uma implantação
